FROM node:18-slim as app-builder
WORKDIR /app
COPY . .
ARG ZOEKT_URL
RUN ZOEKT_URL=$ZOEKT_URL npm install \
    && npm run build \
    && npm install --omit=dev

FROM gcr.io/distroless/nodejs18-debian11
WORKDIR /app
COPY package.json .
COPY --from=app-builder /app/build build
COPY --from=app-builder /app/node_modules node_modules
ENTRYPOINT ["/nodejs/bin/node", "build"]
